version: "3.8"

services:
   jenkins:
     image: jenkins/jenkins:lts
     privileged: true
     user: root
     restart: always
     ports: 
       - "8080:8080"
       - "5000:5000"
     container_name: jenkins
     volumes:
       - /jenkins:/var/jenkins_home